# .github/workflows/publish-test.yml
name: Publish to TestPyPI

on:
  push:
    branches: [master]
    paths:
      - "pyproject.toml"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
